### ISSUE TITLE
5xx when no base page widgets are found?

### ISSUE THREAD

**Issue by jacksontj** [ghowland/web6.0#21]
Right now web6 returns a 404 in the case that a web_site_page exists but there are no base page widgets (https://github.com/ghowland/web6.0/blob/master/web6/web6.go#L522). This seems like the response should either be 5xx (some internal server error) or a blank page -- not a 404; as the resource was defined in the database, it just has nothing in it.

**Comment by zelin-l** [comment]
Make sense - changed the response from 404 to 500 internal server error since the page cannot be rendered without the base widget template: https://github.com/ghowland/web6.0/pull/23
